apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airbyte-external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: airbyte-secret-store
    kind: SecretStore
  target:
    name: airbyte-config-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: airbyte_eso


